name: Optimizer images
on:
  pull_request:
    branches:
      - main
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.gif'
jobs:
  crush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compress Images
        uses: calibreapp/webp-optimizer@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}


