name: Optimizer images
on:
  pull_request:
    branches:
      - main
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.gif'

jobs:
  crush:
    permissions:
      pull-requests: write
      checks: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.AUTH_TOKEN_GRANTED }}
